# fly.toml app configuration file generated for mod-points-bot on 2024-01-13T01:15:26-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mod-points-bot"
primary_region = "sea"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
